import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TopNav from "@/components/TopNav";
import SideNav from "@/components/SideNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Assignment app ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="relative">
        <TopNav />
        <div className=" flex items-center w-full justify-center my-8">
          {children}
        </div>
        <div className=" absolute top-3  left-0">
          <SideNav />
        </div>
      </body>
    </html>
  );
}
